name: foo bar
on: push

jobs:
    build:
      name: Just a bug demo
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/emobotics-dev/yocto-ci-docker:latest
      steps:
      - name: Get current date
        id: date
        run: |
          echo "BUILD_TIME=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
          echo ${{ env.BUILD_TIME }}
